name: "Setup hledger"
description: "Download and install hledger binary"
branding:
  icon: "dollar-sign"
  color: "yellow"
inputs:
  version:
    description: "Version to install."
    required: false
outputs:
  version:
    description: "Installed version."
    value: ${{ steps.install.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: install-version
      shell: bash
      if: ${{ inputs.version != null }}
      run: |
        ${{ github.action_path }}/src/install.sh --version "${{ inputs.version }}" --dist "$HOME/.local/bin"
        echo "version=$($HOME/.local/bin/hledger --version)" >> $GITHUB_OUTPUT
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - id: install-default-version
      shell: bash
      if: ${{ inputs.version == null }}
      run: |
        ${{ github.action_path }}/src/install.sh --dist "$HOME/.local/bin"
        echo "version=$($HOME/.local/bin/hledger --version)" >> $GITHUB_OUTPUT
        echo "$HOME/.local/bin" >> $GITHUB_PATH
